/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PERIPHERALS_H_
#define _PERIPHERALS_H_

/***********************************************************************************************************************
 * Included files
 **********************************************************************************************************************/
#include "fsl_common.h"
#include "fsl_clock.h"
#include "fsl_lpspi.h"
#include "fsl_semc.h"
#include "fsl_flexspi.h"
#include "fsl_lpi2c.h"

#if defined(__cplusplus)
extern "C" {
#endif /* __cplusplus */

/***********************************************************************************************************************
 * Definitions
 **********************************************************************************************************************/
/* Definitions for BOARD_InitPeripherals functional group */
/* BOARD_InitPeripherals defines for LPSPI1 */
/* Definition of peripheral ID */
#define LPSPI1_PERIPHERAL LPSPI1
/* Definition of clock source */
#define LPSPI1_CLOCK_FREQ 105600000UL
/* BOARD_InitPeripherals defines for SEMC */
/* Definition of peripheral ID. */
#define SEMC_PERIPHERAL SEMC
/* Definition of peripheral ID */
#define FLEXSPI_PERIPHERAL FLEXSPI
/* FLEXSPI interrupt vector ID (number). */
#define FLEXSPI_IRQN FLEXSPI_IRQn
/* FLEXSPI interrupt handler identifier. */
#define FLEXSPI_IRQHANDLER FLEXSPI_IRQHandler
/* BOARD_InitPeripherals defines for LPI2C1 */
/* Definition of peripheral ID */
#define LPI2C1_2_PERIPHERAL LPI2C1
/* Definition of clock source */
#define LPI2C1_2_CLOCK_FREQ 60000000UL
/* Transfer buffer size */
#define LPI2C1_2_MASTER_BUFFER_SIZE 1
/* Definition of slave address */
#define LPI2C1_2_MASTER_SLAVE_ADDRESS 0

/***********************************************************************************************************************
 * Global variables
 **********************************************************************************************************************/
extern const lpspi_master_config_t LPSPI1_config;
extern semc_config_t SEMC_config;
extern semc_sdram_config_t SEMC_sdram_struct;
extern const flexspi_config_t FLEXSPI_config;
extern const lpi2c_master_config_t LPI2C1_2_masterConfig;
extern lpi2c_master_transfer_t LPI2C1_2_masterTransfer;
extern uint8_t LPI2C1_2_masterBuffer[LPI2C1_2_MASTER_BUFFER_SIZE];
extern lpi2c_master_handle_t LPI2C1_2_masterHandle;

/***********************************************************************************************************************
 * Initialization functions
 **********************************************************************************************************************/

void BOARD_InitPeripherals(void);

/***********************************************************************************************************************
 * BOARD_InitBootPeripherals function
 **********************************************************************************************************************/
void BOARD_InitBootPeripherals(void);

#if defined(__cplusplus)
}
#endif

#endif /* _PERIPHERALS_H_ */
