/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

/*
 * Copyright 2018-2024 NXP
 * All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __RTE_DEVICE_H
#define __RTE_DEVICE_H

/***********************************************************************************************************************
 * Driver name mapping
 **********************************************************************************************************************/
/* Enable peripheral */
#define RTE_SPI2 1

/***********************************************************************************************************************
 * Driver configuration
 **********************************************************************************************************************/
/* PCS to SCK delay. */
#define RTE_SPI2_PCS_TO_SCK_DELAY 0
/* SCK to PCS delay. */
#define RTE_SPI2_SCK_TO_PSC_DELAY 0
/* Between transfer delay. */
#define RTE_SPI2_BETWEEN_TRANSFER_DELAY 0
/* Peripheral chip select. */
#define RTE_SPI2_MASTER_PCS_PIN_SEL kLPSPI_MasterPcs1


#endif /* __RTE_DEVICE_H */
